version: "3.8"
services:
  web:
    build:
      context: "./doc-share"
    ports:
      - "3000:80"

    image: docshare:frontend

  api:
    build:
      context: "./api"
    ports:
      - "5000:5000"
    image: docshare:backend
