version: "3.3"
services:
  web:
    build:
      context: ./doc-share
    ports:
      - "80:3000"

    image: docshare:frontend

  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    image: docshare:backend

  reverse-proxy:
    image: valian/docker-nginx-auto-ssl:1.0.0
    container_name: reverse-proxy
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.ssl-data:/etc/rest-auto-ssl
    environment:
      SITES: "declr.dev:443;declr.dev:80"
      FORCE_HTTPS: "true"
    depends_on:
      - web
      - api
volumes:
  .ssl-data:
