version: "3.4"

services:
  web:
    image: nginx:1.14.2-alpine
    restart: always
    volumes:
      - ./doc-share/build/:/public_html
      - ./conf.d:/etc/nginx/conf.d
      - ./dhparam:/etc/nginx/dhparam
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
      - 80:80
      - 443:443
  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email noahjacknichols@gmail.com --agree-tos --no-eff-email -d declr.dev
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./cerbot/data:/usr/share/nginx/html/letsencrypt
